// Embeds lodash (MIT, lodash.com/license) into src/scripts/lodash.generated.ts so Postman-style scripts can use
// `_` and require('lodash') in the QuickJS sandbox, like in Postman. Loaded only by scripts that use it.
//
// Run: npm run lodash -w @testpion/core   (after updating the lodash dependency)
const { readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');

const pkg = require('lodash/package.json');
const src = readFileSync(require.resolve('lodash/lodash.min.js'), 'utf8');
const out = [
  `// Generated by scripts/make-lodash.cjs from lodash ${pkg.version} (MIT, lodash.com/license). Do not edit.`,
  `export const LODASH_VERSION = ${JSON.stringify(pkg.version)};`,
  `export const LODASH_SOURCE = ${JSON.stringify(src)};`,
  '',
].join('\n');
writeFileSync(join(__dirname, '..', 'src', 'scripts', 'lodash.generated.ts'), out);
console.log(`lodash ${pkg.version}: ${src.length} bytes`);
