// The main tour: every view, menus, dialogs, request editors, runs, monitors, AI Lab, settings and accessibility.
// Part of the end-to-end UI regression suite (see e2e/run-e2e.mjs and .claude/skills/ui-regression).
const { withExpect } = require('../lib.cjs');
// [name, page code (uses window.__t), take a screenshot?]
const steps = [
  ['home', `__t.view('Home')`],
  ['home-activity', `(async () => { await __t.sleep(1200); const a = document.querySelector('section[aria-label=Activity]'); a?.scrollIntoView(); await __t.sleep(400); return a ? a.innerText.slice(0, 160) : 'NO ACTIVITY'; })()`],
  ['sidebar', `__t.requests()`],
  ['header-new', `(async () => { await __t.esc(); const b = document.querySelector('aside[aria-label="Collections explorer"] button[aria-label="New"]'); b?.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, button: 0, pointerType: 'mouse' })); await __t.sleep(800); return [...document.querySelectorAll('[role=menuitem]')].map((m) => m.textContent.trim()).join(' | '); })()`],
  ['header-import', `__t.header('Import')`],
  ['header-export', `__t.header('Export')`],
  ['menu-collection', `__t.menu('HTTP basics (httpbin)')`],
  ['rest-open', `(async () => { await __t.esc(); await __t.expand('HTTP basics (httpbin)'); await __t.expand('Requests & responses'); return __t.open('GET with query parameters'); })()`],
  ['menu-category', `__t.menu('REST')`, false],
  ['menu-folder', `__t.menu('Requests & responses')`],
  ['menu-request', `__t.menu('GET with query parameters')`, false],
  ['rest-breadcrumb', `(async () => { await __t.esc(); return __t.crumb(); })()`, false],
  ['rest-send', `(async () => { await __t.button('Send'); await __t.sleep(5000); return __t.visibleText(); })()`],
  ['rest-headers', `__t.tab('Headers')`],
  ['rest-body', `__t.tab('Body')`],
  ['rest-scripts', `__t.tab('Scripts')`],
  ['rest-tests', `__t.tab('Tests')`],
  ['rest-settings', `__t.tab('Settings')`],
  ['rest-var-popover', `__t.varPopover()`],
  ['tab-menu', `__t.tabMenu()`],
  ['graphql', `(async () => { await __t.esc(); await __t.expand('GraphQL (public APIs)'); const cat = [...document.querySelectorAll('[data-tree-row]')].find((b) => /^GQLGraphQL/.test(b.textContent.trim())); if (cat?.getAttribute('aria-expanded') === 'false') cat.click(); await __t.sleep(500); await __t.expand('Countries'); await __t.open('Country by code'); await __t.sleep(1000); return __t.visibleText(); })()`],
  ['grpc', `(async () => { await __t.esc(); await __t.expand('gRPC (grpcb.in)'); await __t.expand('gRPC'); await __t.open('Say hello (unary)'); return __t.visibleText(); })()`],
  ['menu-grpc', `__t.menu('Say hello (unary)')`],
  ['websocket', `(async () => { await __t.esc(); await __t.expand('WebSocket & MQTT'); await __t.open('Postman echo (JSON)'); return __t.visibleText(); })()`],
  ['mcp', `(async () => { await __t.esc(); await __t.open('Weather (offline mock)'); return __t.visibleText(); })()`],
  ['mcp-connect', `(async () => { await __t.button('Connect'); await __t.sleep(3500); return __t.visibleText(); })()`],
  ['mcp-settings', `__t.tab('Settings')`],
  ['menu-mcp', `__t.menu('Weather (offline mock)')`, false],
  ['apidef', `(async () => { await __t.esc(); await __t.open('petstore.json'); return __t.visibleText(); })()`],
  ['apidef-coverage', `__t.tab('Coverage')`],
  ['apidef-compare', `__t.tab('Compare versions')`],
  ['collection-settings', `(async () => { await __t.esc(); await __t.requests(); await __t.open('GET with query parameters'); const c = [...document.querySelectorAll('nav[aria-label="Where this request is saved"] button')].find((x) => x.offsetParent); c?.click(); await __t.sleep(1800); return __t.visibleText(); })()`],
  ['collection-overview', `(async () => { await __t.tab('Overview'); await __t.sleep(1200); return (document.querySelector('main')?.innerText.match(/REQUEST HEALTH[^]{0,120}/i)?.[0] ?? 'NO HEALTH'); })()`],
  ['runner', `(async () => { await __t.tab('Run'); return __t.visibleText(); })()`],
  ['tests-run', `(async () => { await __t.esc(); const r = await window.aps.invoke('tests.run', { paths: ['offline.suite.yaml'], name: 'Offline suite' }); await __t.sleep(20000); return r?.runId ?? 'NO RUN'; })()`, false],
  ['tests', `__t.view('Tests')`],
  ['runs-overview', `(async () => { const t = [...document.querySelectorAll('[role=tab]')].filter((x) => x.textContent.trim().startsWith('Runs')).pop(); t?.click(); await __t.sleep(1500); return [...document.querySelectorAll('main section h3')].map((h) => h.textContent).join(', ') || 'NO CHARTS'; })()`],
  ['run-charts', `(async () => { const r = [...document.querySelectorAll('main button')].find((b) => b.querySelector('.bg-ok, .bg-bad') && b.closest('[class*=overflow-auto]')); r?.click(); await __t.sleep(2000); const c = [...document.querySelectorAll('[role=tab]')].find((x) => x.textContent.trim() === 'Charts'); c?.click(); await __t.sleep(1500); return [...document.querySelectorAll('main section h3')].map((h) => h.textContent).join(', ') || 'NO CHARTS'; })()`],
  ['test-history', `(async () => { await __t.tab('Results'); await __t.sleep(800); const b = document.querySelector('main button[title] span.w-14')?.closest('button'); b?.click(); await __t.sleep(1000); const ok = await __t.tab('History'); await __t.sleep(1500); return ok ? (document.querySelector('main')?.innerText.match(/(passed \\d+ of[^\\n]*|No earlier runs of this test)/)?.[0] ?? 'NO HISTORY') : 'NO HISTORY TAB'; })()`],
  ['monitors', `__t.view('Monitors')`],
  ['monitor-tab-run', `(async () => { const el = [...document.querySelectorAll('main *')].find((x) => x.children.length === 0 && x.textContent.trim() === 'Public APIs health' && !x.closest('[role=tablist]')); (el?.closest('button,[role=button],li') ?? el)?.click(); await __t.sleep(1500); await __t.button('Run now'); await __t.sleep(12000); const tabs = [...document.querySelectorAll('[role=tablist][aria-label="Open monitors"] [role=tab]')].map((t) => t.textContent.trim()); const charts = [...document.querySelectorAll('main section h3')].map((h) => h.textContent); return 'tabs: ' + tabs.join(', ') + ' | charts: ' + charts.join(', '); })()`],
  ['monitors-new', `(async () => { const b = [...document.querySelectorAll('button[aria-label]')].find((x) => /new monitor|add monitor/i.test(x.getAttribute('aria-label'))); b?.click(); await __t.sleep(1000); return (document.querySelector('main')?.innerText.match(/New monitor[\s\S]{0,40}/)?.[0] ?? 'NONE'); })()`],
  ['load', `__t.view('Load')`],
  ['ai-lab', `__t.view('AI Lab')`],
  ['evaluations', `__t.view('Evaluations')`],
  ['environments', `__t.view('Environments')`],
  ['history', `__t.view('History')`],
  ['traces', `__t.view('Traces')`],
  ['settings', `__t.view('Settings')`],
  ['timeline-phases', `(async () => { await __t.esc(); await __t.requests(); await __t.open('GET with query parameters'); await __t.sleep(800); await __t.button('Send'); await __t.sleep(5000); await __t.tab('Timeline'); await __t.sleep(600); const t = document.querySelector('main')?.innerText ?? ''; return ['DNS lookup', 'TCP connect', 'TLS handshake', 'waiting (TTFB)', 'Certificate'].map((x) => (t.includes(x) ? x : 'NO ' + x)).join(', '); })()`],
  ['trace-phases', `(async () => { await __t.tab('Trace'); await __t.sleep(1200); const t = document.querySelector('main')?.innerText ?? ''; return (t.match(/\\d+ spans/)?.[0] ?? 'NO SPANS') + (t.includes('TLS handshake') ? ', TLS span' : ', NO TLS span'); })()`],
  ['mcp-usage', `(async () => { await __t.esc(); await __t.open('Weather (offline mock)'); await __t.sleep(1000); const ok = await __t.tab('Usage'); await __t.sleep(1200); return ok ? (document.querySelector('main')?.innerText.match(/(CALLS PER TOOL[^\\n]*|No tool calls yet)/i)?.[0] ?? 'NO USAGE') : 'NO USAGE TAB'; })()`],
  ['ai-usage', `(async () => { await __t.view('AI Lab'); await __t.sleep(800); const ok = await __t.tab('Usage'); await __t.sleep(1200); return ok ? (document.querySelector('main')?.innerText.match(/(Prompts run[^]{0,40}|No prompts run yet)/)?.[0]?.split('\\n').join(' ') ?? 'NO USAGE') : 'NO USAGE TAB'; })()`],
  ['home-certificates', `(async () => { await __t.view('Home'); await __t.sleep(1500); const h = [...document.querySelectorAll('main section > header')].find((x) => x.textContent.trim().startsWith('Certificates')); h?.scrollIntoView({ block: 'center' }); await __t.sleep(400); return h ? h.parentElement.innerText.split('\\n').slice(0, 5).join(' | ') : 'NO CERT CARD'; })()`],
  ['home-attention', `(async () => { await __t.view('Home'); await __t.sleep(1500); const s = document.querySelector('main section[aria-label="Needs attention"]'); return s ? s.innerText.split(String.fromCharCode(10)).slice(0, 4).join(' | ') : 'card hidden: nothing needs attention'; })()`],
  ['tests-latest', `(async () => { await __t.view('Tests'); await __t.sleep(1200); const f = [...document.querySelectorAll('main *')].find((x) => x.children.length === 0 && x.textContent.trim() === 'weather-mock.yaml'); (f?.closest('button') ?? f)?.click(); await __t.sleep(2000); const rows = [...document.querySelectorAll('main button[title^="Latest result"]')].filter((b) => b.offsetParent !== null); return rows.length ? rows.length + ' tests show their latest result' : 'NO LATEST RESULTS'; })()`],
  ['traces-errors', `(async () => { await __t.view('Traces'); await __t.sleep(1200); const box = [...document.querySelectorAll('main label')].find((l) => l.textContent.trim() === 'Errors')?.querySelector('input'); if (!box) return 'NO ERRORS FILTER'; box.click(); await __t.sleep(1200); const n = document.querySelector('main')?.innerText.match(/(\\d+) traces/)?.[1]; box.click(); await __t.sleep(600); return 'errors filter works: ' + (n ?? '0') + ' traces with errors'; })()`],
  ['history-timing', `(async () => { await __t.view('History'); await __t.sleep(1200); const b = [...document.querySelectorAll('main button')].find((x) => x.offsetParent !== null && x.textContent.includes('httpbin.org')); b?.click(); await __t.sleep(1000); return document.querySelector('main [role=img][aria-label^="Timing"]')?.getAttribute('aria-label') ?? 'no timing shown (entry has none)'; })()`],
  ['palette', `(async () => { await __t.esc(); return __t.key('k', { ctrlKey: true }); })()`],
  ['search', `(async () => { await __t.esc(); return __t.key('F', { ctrlKey: true, shiftKey: true }); })()`],
  ['shortcuts', `(async () => { await __t.esc(); document.body.focus(); window.dispatchEvent(new KeyboardEvent('keydown', { key: '?', bubbles: true })); await __t.sleep(900); return (document.querySelector('[role=dialog]')?.innerText ?? 'NONE').slice(0, 60); })()`],
  ['a11y', `(async () => { await __t.esc(); const name = (el) => (el.getAttribute('aria-label') || el.getAttribute('title') || el.textContent || '').trim() || (el.labels && [...el.labels].map((l) => l.textContent).join('').trim()) || el.getAttribute('placeholder') || ''; const out = []; for (const v of ['Home', 'Collections', 'Tests', 'Monitors', 'Load', 'AI Lab', 'Evaluations', 'Environments', 'History', 'Traces', 'Settings']) { await __t.view(v); await __t.sleep(900); const bad = [...document.querySelectorAll('button, [role=button], input:not([type=hidden]), select, textarea')].filter((el) => el.offsetParent && !el.closest('[aria-hidden=true]') && !name(el)).length; if (bad) out.push(v + ': ' + bad); } return out.length ? 'UNNAMED ' + out.join(', ') : 'all controls named'; })()`, false],
];

module.exports = withExpect(steps, { a11y: /all controls named/ });
